/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BarangCtrl;
import controller.JenisCtrl;
import controller.KategoriCtrl;
import controller.Transaksi;
import controller.LoginController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Barang;
import model.Jenis;
import model.Kategori;
import model.Login;
import model.Transaksi_Pesan;
/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame {

    private Transaksi transaksi;
    private LoginController loginctrl;
    private JenisCtrl jenisctr;
    private KategoriCtrl kategoriCtrl;
    private BarangCtrl barangCtrl;
    
    /**
     * Creates new form Admin
     * @throws java.sql.SQLException
     */
    public Admin() throws SQLException {
        initComponents();
        this.loginctrl = new LoginController();
        this.jenisctr = new JenisCtrl();
        this.kategoriCtrl = new KategoriCtrl();
        this.barangCtrl = new BarangCtrl();
        this.transaksi = new Transaksi();
        this.showTblLogin();
        this.showTblJenis();
        this.showTblKategori();
        this.showTblBarang();
        this.showTblTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Panel = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogin = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJenis = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        Menu = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLogin);

        Panel.addTab("Login", jScrollPane1);

        tblJenis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblJenis);

        Panel.addTab("Jenis", jScrollPane2);

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblKategori);

        Panel.addTab("Kategori", jScrollPane3);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblBarang);

        Panel.addTab("Barang", jScrollPane4);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblTransaksi);

        Panel.addTab("Transaksi", jScrollPane5);

        Menu.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblJenis;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTable tblLogin;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables

    private void showTblLogin() throws SQLException {
        DefaultTableModel dtmLogin = new DefaultTableModel(new String[]{"ID Login", "Username", "Password"}, 0);
        dtmLogin.setRowCount(0);
        for (Login p : this.loginctrl.getDataLogin(null)){
            dtmLogin.addRow(new String[]{p.getId_login().toString(),p.getUsername(),p.getPassword()});
        }
        tblLogin.setModel(dtmLogin);
    }

    private void showTblJenis() throws SQLException {
        DefaultTableModel dtmJenis = new DefaultTableModel(new String[]{"ID Jenis", "Nama Jenis"}, 0);
        dtmJenis.setRowCount(0);
        for (Jenis p : this.jenisctr.getDataJenis(null)){
            dtmJenis.addRow(new String[]{p.getId_jenis().toString(),p.getNama_Jenis()});
        }
        tblLogin.setModel(dtmJenis);
    }

    private void showTblKategori() throws SQLException {
        DefaultTableModel dtmKategori = new DefaultTableModel(new String[]{"ID Kategori", "Nama Kategori"}, 0);
        dtmKategori.setRowCount(0);
        for (Kategori p : this.kategoriCtrl.getDataKategori(null)){
            dtmKategori.addRow(new String[]{p.getId_Kategori().toString(),p.getNama_Kategori()});
        }
        tblLogin.setModel(dtmKategori);
    }

    private void showTblBarang() throws SQLException {
        DefaultTableModel dtmBarang = new DefaultTableModel(new String[]{"ID Barang","Nama Kategori","Nama Jenis", "Nama Barang","Harga Satuan"}, 0);
        dtmBarang.setRowCount(0);
        for (Barang p : this.barangCtrl.getDataBarang(null)){
            dtmBarang.addRow(new String[]{p.getId_barang().toString(),p.getKategori().getNama_Kategori(),p.getJenis().getNama_Jenis(),p.getNama_barang(),p.getHarga_Satuan().toString()});
        }
        tblLogin.setModel(dtmBarang);
    }

    private void showTblTransaksi() throws SQLException {
        DefaultTableModel dtmTransaksi = new DefaultTableModel(new String[]{"ID Transaksi","Nama Barang","Username", "Tanggal Transaksi","Jumlah Barang","Total Harga"}, 0);
        dtmTransaksi.setRowCount(0);
        for (Transaksi_Pesan p : this.transaksi.getDataPemesanan(null)){
            dtmTransaksi.addRow(new String[]{p.getId_transaksi().toString(),p.getBarang().getNama_barang(),p.getLogin().getUsername(),p.getTanggal_transaksi().toString(),p.getJum_barang().toString(),p.getHarga_Total().toString()});
        }
        tblLogin.setModel(dtmTransaksi);
    }
}
